mapBanner = """
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOccOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'.oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMWx..kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWko0MMMMMMMMMMMMMMMMMMMNd'.lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc:0WMMMMMMMMMMMMMMMMMWO:oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk:dNMMMMMMMMMMMMMMMMMMOldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMWX0KNkxXMMMMMMMMMMMMMMMMN0;.:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWXX0dkkdKWXKNWMNx''xxd0XWMMMMMMMMMMMMMWx',cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW00MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWNO,.,'oXKd;lOO:. ...;xWMMMMMMMMMMMMMWxc0WMMMMMMMMMMMMNkxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWNd'..;OWKc...     'dXMMMMMMMMMMMMMMW00WMMMMMMMMMMMMMNo;kWMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNMMMMWXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWN0kl..'kWMM0,      .:0MMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMO;lKNKXMMMWOd0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXdoKWNKxcdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWNOl:oo:cOMMMXc.,ll;. .:kNMMMMMMMMMMMMMWNMMMMMMMMMMMMMMMWk,;OklOMMWk,:KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c..,oc..;d0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNKkx0KodNMMWO,'cdOd...'dNMMMMMMWMMMMWKKWMMMMMMMMMMMMMMMXxdl':0XNWx'oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;. ..;cdKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWWMNkc..oXW0:..cdl:. ..':lxdoO00NKKW0oo0WMMMMMMMMMMMMMMWKXk':O0XXxkXWMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMWNO;.';kNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWKxk0d'...:l,...',.   .'''......';';o: .lKNMMMMMMMMMMMMMWKXXc:ooxlxWMMMMWXXXWMMMMMMMMMMMMMWkkNMMMMMMMMMMMMMMMMMMWNO:.'dXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMN0OKKOl'............       ....  .'.   ....,d0NMMMMMMMMMMMMMWKK0:,;;;.oXMMMWk;l0WMMMMMMMMMMMMMWxxNMMMMMMMMMMMMMMMMMW0:. .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMNO0X0xOKK0kdl;...... ................    .. ...,;,.'...lKWMMMMMMMMMMMMMMMMXko...,.,xNMWNkcoKWMMMMMMMMMMMMMMMK0WMMMMMMMMMMMMMMMXkd:. .,dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMM0co0K0kxl:;'.......    .';,....... ..........,;::;,,,:k0NMMMMMMMMMMMWWNKKNK:......,k0OxxkXWMMMMMMMMMMMMMMMMMNKNMMMMMMMMMWWMMMMKc..'dKXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWWWMMMMNk;.cx00ko:,.,oco0XKkkxo:.... .........,::;;;,oWMMMMMMMMMNNMMWOd:',,..'....'c;:OXNWMMMMMMMMMMMMMMMMXKXKOKXKXWNNOcoXMMMWk..;oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMW00NMMWOlckO0NNNMMMMMNOd;......  ..','';c:::,:KMMMMMMMMMX0KXk:'.    .;;''...'dK00XMMMMMMMMMMMMMMMMKoc:'l0o,:;;' .dXWW0:;xNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWNNMMMMMMMMMMMN0kxlc:.    ...';;:c:;:c;dNMMMMMMMMMO:co;.    .....';;..';:lOXWMMMMMMMMMMMMMMWk. ..:,.... ...:ol,,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWK;   .....,;:c::::;;kWMMMMMMMWKd,...    .....,;,,,';:cdONMMMMMMMMMMMMMMMk'....','.....,:;',kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.,......,:;;::::,';xXMMMMMMW0c.. .........,,...,xXNWWMMMMMMMMMMNOKX0XWk'. ..,:;',,,,;c;'lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW00XO,  ...,:cc;;;;;:;lONMMMMMNd'  ....'.. ......:KMMMMMMMMMMMMMWx,oN0oc;....',:;;;;;',;',kWWNX0kONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkcxXMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,  ....,ccc:;;:c:;;cxxxxdl'......... .',,''..lKKKXMMMMMMMMMMO;'okc',,,,,,,,;;;:;,;'..'cccdk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMK; ,OWMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXKNMMW0x,.....',;;;;,'''.......   ..  ...  .;:,.''.';::xWMWMMMMMMW0c.';:::;;;::,';:;;,,,....;dOXNXNMMMMMMMMMMMMMMMMMXOKMMMMMMMMMMMMMWKKNOlxO:...;x0N
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKO0O00l.;okkkl'...............''....... ..      .';;,',;;,,,',lx0WMX00koc;:cllc:;:cll:;;'..'''.....;lodx0WMMMMMMMMMMMMMMMWk:OMMNXWMMMMMMMMXl,c;...,cdkOKNW
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0O00d,.,;oxxl.   ........',,,,,,'.......     .',,,;;;;,;;,,,';dxoc;;::lccooooodolll;.......'.   .oKXNWMMMMMMMMMMMMMMMMMWo;kKk:;OMMMMMMMWk,..',..dWMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN00KKXNWWMNd................',;,'.......  ..,;;;,;;;:;;;;;,,;,..,:loddddoddddxddoc,.';;;,...  .c0XNWMMMMMMMMMMMMMMMWKKXl.....:0WNOod0Od;ckO0XKO0NMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKNMMMMMMWO,........... ....................,;:::;,;:::cc:;,'...;:coddddlccodooool:cclccl,    .,ckNWMMMMMMMMMMMMMMMMNOl'....,xNW0c..,,lONMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKOo,..'''......     .  ...............,:cc;;:cccccc:'. ..:loooddddoloooddolloolclc,',;;,,:ox0WMMMMMMMMMMMMMMMNd. . .'';cc::oxd:,:xNMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKx,....'''''.....          ..... ........'';:ccc;,;;,',.'::codolccooollollolloollc:':ONNNXXNK0NMMMMMMMMMMMMMMMWx'....',:c;;oO0XNNK0KWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl;. ......''.....    ..          ...',,''....';c:..'',,;,:lc,;coolollolclcc::cloollc:;oXMMMMMMMMMMMMMMMMMMMMW0xc'...'xKXWMXkkNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'    .........,:loxkOOkd,.        ..''..,'.'...:;.';;;:llcc:,'.';:lolc:clllccllolclodoccx0KNMMMMMMMMMMMMMMWXk;....,lkXMMMMMMWWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMNKOl.....   ....':xXWMMMMMMMNd,:ccddc'.  .....';::;'..,;;;,,cc;,:;'....;cc::llolloollc::ccll:,',l0NWMMMMMMMMWXOo;....:kKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0x,..............dNWMMMMMMMMMXKKXNNWWNd. ...'',,;:c::;,;,.....,,,;;;;;,,;'';lolc::llll:;;;;;;:;,'';:dKXNWWN0d:,''..,:cdKMMMMMWX0KWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWNXNN0OOKNMMMWXKOc............... .kMMMMMMMMMMMMMMWX0kxdc.  ......,:ccccc;,.......',,,;;:;;,.'cc:,'',;;:c:'.:ddol:'',,,;:cloc,..''',dKNWWMMMMWXd;c0WMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMW0ddO0x,..;lddl;,.    ..........;:..xWMMMMMMMMMMMMMMMXx:.      ....';cc:::'.........',..,;;::'.,;'..',cxKNXo;o0WWXd'.',:;,'''...,,..lNMMMMMMWkcclx0NWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWXNWWXOOXXo.   ...,:c:. ..........;OO'.lNMMMMMMMMMMWKxkO0x,   .  ......;:c::::,....  .',;..,,';;,''...'oONMMMMXx:'cONWXKXXXX0ko;...'c:'lXMMMMMNx,:0WMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMN0l:xK0c..,....,::oKWW0,  . .l0Kxc,oKx:,kWMMMMMMMMKkko'....    ....''..';;:c:;::'... .........',,,'....oXMMMMMMMNd..cXMMMMMMMMMW0,.....'xKKXWMKc..dNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMXo'. ......'. 'xXWNWMMWO'...c0NMMMNkOWW0d0MMMMMMMMWk:;'.''..''.   ....  .;cc::;;;'..  .... ...';,,,,,;dkOOKWMMMMMWN0xcoKMMMMMMMMNk,.... .cdccOKl. ;ONMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMNl.  .lkOkkK0lcOWMMMMMXc...cXMMMMMMNNMMNXWMMMMMMMMMWXO;...;dkc.    .  ..',::'..,,,,..   .....',;;,,',kWMMWNWMMMMMMMMW0dONMMMMMMMN0ko'... ..'.... .dXNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMM0c'':kNMMMMMMWNWMMMMMXc.  .dWMMMMMMMMMMMMMMMMMMMMMMMWd':lxXNkc,..     ...,:;. .','....  .....',,'....oNMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:....  .      .:okKNNXNWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMNXXXWMMMMMMMMMMMMMMMWk'  '::kNMMMMMMMMMMMMMMMMMMMMMMWKOXNXOddxc'...  ........  ............. .... 'cldOKWMMMMMMMMMMMMMMMMMMMMMMMMW0:.....   ..   .....,:clx0KNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl;..l0xOWMMMMMMMMMMMMMMMMMMMMMMMMMWKkOKNkoddxdc',;..... .........  ......'...',ckXNWMMMMMMMMMMMMMMMMMMMMMMMMWKkxl,''.. ...  .''''':odxxdOKXXNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkOKl..dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXxxXWNWMWKKKo,;lc'..;xxoo:'..,;;;,'';,:xxcckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKko,..'. ......;OWMWWNNWWNWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMWx';kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd,,kWMMMMMMWXXKX0l',dNMMMMNd...'....,;;:OMXOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc...'...'....:KMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOKMMMMMMMMMMMMMMMMMMMMMMMMMNXKkkdc..c0WMMMMMMWWMMWk.'kWMMMMMWkc'.....','.'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl........  ..'kWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOool'.. .xWMMMMMMMMMMMXo;dNMMMMMMMXx;ckOOd,.....dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kd:,'...     .cXMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXWK: .,xKWMMMMMMMMMW0ldXMMMMMMMMWKddXMMKddl...'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK0NWX0dcc,......,lOXWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl,oNMMMMMMMMMMMWKKNMMMMMMMMMWNNMMMWKkXXc..,oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXWMMWNKOOkc,':c..cOWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKc..';xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMX0Kkc,.:k00KXWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlcOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c..'.,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW0okNMNKKWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWko0O0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo....'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXNMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdxNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl....ck0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl,.'o0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'.,coKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNMMO::xK0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMWxdXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO;;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dxo.,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWNdoXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0ooXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;.,d0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXocOWWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""

bannerExampleStart = """
#     #                         #######                                                  
##   ##   ##   #####   ####     #       #    #   ##   #    # #####  #      ######  ####  
# # # #  #  #  #    # #         #        #  #   #  #  ##  ## #    # #      #      #      
#  #  # #    # #    #  ####     #####     ##   #    # # ## # #    # #      #####   ####  
#     # ###### #####       #    #         ##   ###### #    # #####  #      #           # 
#     # #    # #      #    #    #        #  #  #    # #    # #      #      #      #    # 
#     # #    # #       ####     ####### #    # #    # #    # #      ###### ######  ####  
"""

bannerExampleEnd = """
#######                                                       ###
   #    #    #   ##   #    # #    #    #   #  ####  #    #    ###
   #    #    #  #  #  ##   # #   #      # #  #    # #    #    ###
   #    ###### #    # # #  # ####        #   #    # #    #     #
   #    #    # ###### #  # # #  #        #   #    # #    #
   #    #    # #    # #   ## #   #       #   #    # #    #    ###
   #    #    # #    # #    # #    #      #    ####   ####     ###
                                                                  
"""
