

# This file was *autogenerated* from the file PlanarMapGenerator.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8)
load("PlanarMap.sage")

def cube():
	"""Returns the standard cube map."""
	return PlanarMap(adj = [(_sage_const_5 ,_sage_const_4 ,_sage_const_2 ),(_sage_const_1 ,_sage_const_3 ,_sage_const_6 ),(_sage_const_4 ,_sage_const_7 ,_sage_const_2 ),(_sage_const_8 ,_sage_const_3 ,_sage_const_1 ),(_sage_const_8 ,_sage_const_1 ,_sage_const_6 ),(_sage_const_5 ,_sage_const_2 ,_sage_const_7 ),(_sage_const_3 ,_sage_const_8 ,_sage_const_6 ),(_sage_const_7 ,_sage_const_4 ,_sage_const_5 )])

def complete_map(n):
	"""Returns the complete map with n nodes."""

	adj = [((j+i)%n + _sage_const_1  for j in range(n)) for i in range(n)]
	
	return PlanarMap(adj = adj)

